// 거래소 정보 상수
export const EXCHANGES = [
  {
    id: 'bybit',
    name: 'Bybit',
    logo: '/exchanges/bybit/bybit_logo_icon.svg',
    logoSize: 'w-8 h-8',
    paybackRate: 40,
    makerFee: 0.012,
    takerFee: 0.033,
    logoBg: 'bg-blue-100',
    cardBg: 'bg-blue-50',
    description: '수수료 40% 페이백',
    referralUrl: `#`,
  },
  {
    id: 'bitget',
    name: 'Bitget',
    logo: '/exchanges/bitget/bitget_logo_icon.png',
    logoSize: 'w-8 h-8 scale-70',
    paybackRate: 50,
    makerFee: 0.01,
    takerFee: 0.02,
    logoBg: 'bg-yellow-100',
    cardBg: 'bg-yellow-50',
    description: '수수료 50% 페이백',
    referralUrl: `#`,
  },
  {
    id: 'okx',
    name: 'OKX',
    logo: '🪙',
    logoSize: 'text-xl',
    paybackRate: 50,
    makerFee: 0.01,
    takerFee: 0.025,
    logoBg: 'bg-gray-100',
    cardBg: 'bg-gray-50',
    description: '수수료 50% 페이백',
    referralUrl: `#`,
  },
  {
    id: 'bingx',
    name: 'BingX',
    logo: '🔥',
    logoSize: 'text-xl',
    paybackRate: 60,
    makerFee: 0.008,
    takerFee: 0.02,
    logoBg: 'bg-red-100',
    cardBg: 'bg-red-50',
    description: '수수료 60% 페이백',
    referralUrl: `#`,
  },
  {
    id: 'gateio',
    name: 'Gate.io',
    logo: '🚀',
    logoSize: 'text-xl',
    paybackRate: 75,
    makerFee: 0.005,
    takerFee: 0.01,
    logoBg: 'bg-purple-100',
    cardBg: 'bg-purple-50',
    description: '수수료 75% 페이백',
    referralUrl: `#`,
  },
  {
    id: 'binance',
    name: 'Binance',
    logo: '/exchanges/binance/binance_logo_icon.svg',
    logoSize: 'w-8 h-8 object-contain scale-150',
    signupGuideImage: '/exchanges/binance/binance_signup_guide.png',
    verificationGuideImage: '/exchanges/binance/binance_verification_code_guide.png',
    paybackRate: 40,
    makerFee: 0.012,
    takerFee: 0.03,
    logoBg: 'bg-amber-100',
    cardBg: 'bg-amber-50',
    description: '수수료 40% 페이백',
    referralUrl: 'https://accounts.binance.com/en/register?ref=489449343',
  }
] as const

export type ExchangeId = typeof EXCHANGES[number]['id']
